//
// Generated file, do not edit! Created by opp_msgtool 6.1 from Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Packet;
/**
 * Enum generated from <tt>Packet.msg:6</tt> by opp_msgtool.
 * <pre>
 * enum PacketType
 * {
 *     DATA = 0;
 *     DISCOVERY = 1;
 * }
 * </pre>
 */
enum PacketType {
    DATA = 0,
    DISCOVERY = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketType& e) { int n; b->unpack(n); e = static_cast<PacketType>(n); }

/**
 * Class generated from <tt>Packet.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // Represents a packet in the network with SDN capabilities
 * //
 * packet Packet
 * {
 *     int srcAddr \@packetData;
 *     int destAddr \@packetData;
 *     int hopCount \@packetData;
 *     double pathDelay \@packetData;
 *     double pathCost \@packetData;
 * 
 *     // SDN Discovery Fields
 *     int packetType \@packetData = 0;  // 0=DATA, 1=DISCOVERY
 *     double batteryLevel \@packetData = 100.0;  // Node battery level (%)
 *     double distanceToSDN \@packetData = 0.0;   // Distance to SDN controller
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int srcAddr = 0;
    int destAddr = 0;
    int hopCount = 0;
    double pathDelay = 0;
    double pathCost = 0;
    int packetType = 0;
    double batteryLevel = 100.0;
    double distanceToSDN = 0.0;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);

    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getPathDelay() const;
    virtual void setPathDelay(double pathDelay);

    virtual double getPathCost() const;
    virtual void setPathCost(double pathCost);

    virtual int getPacketType() const;
    virtual void setPacketType(int packetType);

    virtual double getBatteryLevel() const;
    virtual void setBatteryLevel(double batteryLevel);

    virtual double getDistanceToSDN() const;
    virtual void setDistanceToSDN(double distanceToSDN);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

